# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='email',
            field=models.CharField(default='somestring', max_length=200),
        ),
    ]
