# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0010_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='flowerid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
