# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0012_auto_20151208_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='flowerid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='userid',
        ),
    ]
