# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0013_auto_20151208_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='flowername',
            field=models.CharField(default='one', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
