# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0015_auto_20151208_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='flowername',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
