# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0017_auto_20151209_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='flower_name',
            field=models.CharField(default='something', max_length=255),
            preserve_default=False,
        ),
    ]
